//
// Created by 李亘杰 on 2021/2/2.
//

#ifndef CUDA_TESTPRJ_NEWNESTEDHELLOWORLD_CUH
#define CUDA_TESTPRJ_NEWNESTEDHELLOWORLD_CUH


class newNestedHelloWorld {

};


#endif //CUDA_TESTPRJ_NEWNESTEDHELLOWORLD_CUH
